### PR TITLE
Update for 4.33

### PR DESCRIPTION
**Pull request by robertmryan**
This wasn't compiling as a result of changes introduced in 4.33.0. 

* This makes changes function signature and import statements in MainActivity; and
* Gradle change for min SDK version.

### CODE REVIEW

**Comment by polarweasel** [comment]
Thank you for this contribution, @robertmryan! This is reflected in changes to the documentation, as well, that will go live this week.

**Comment by pubnubcraig** [comment]
@robertmryan this worked for me when I submitted it and still does. Make sure you build before you run. Not sure if that is it. You may need to make a change to the gradle file to trigger it. I changed 4.+ to 4.0, synced, then changed it back to 4.+ and synced again and it was able to compile/run without error.

**Review by polarweasel — APPROVED** [review]
LGTM. Thank you for this contribution, @robertmryan!

**Comment by polarweasel** [comment]
(Merged this so the sample app reflects Objects v2 usage. The reported issue itself should be solved by Android Studio itself, but the listeners wouldn't be auto-updated...)

**Pull request merged**
